# async> Promise

*이 글은 드림코딩 엘리님의 자바스크립트 강의를 참고하여 공부 목적으로 작성한 글입니다.

(출처: [https://www.youtube.com/watch?v=s1vpVCrT8f4&list=PLv2d7VI9OotTVOL4QmPfvJWPJvkmv6h-2&index=11](https://www.youtube.com/watch?v=s1vpVCrT8f4&list=PLv2d7VI9OotTVOL4QmPfvJWPJvkmv6h-2&index=11))

<br>

## Promise

`Promise`는 비동기를 간편하게 처리할 수 있도록 도와주는 오브젝트이다. <br>
정해진 장시간의 기능이 정상적으로 수행되면 성공한 결과값과 함게 처리된 메시지를 보여준다. 문제가 발생하면 에러를 전달한다. 

<br>

promise를 공부할 때 2가지 포인트(state, producer vs consumer) 가 있다.

### state <br>
process가 무거운 연산을 수행할 때, <br>
수행을 하고 있는 중인지? 수행이 끝나서 성공적으로 마무리 됐는지? 등의 상태(state)를 알고 있는 것이 중요하다.<br><br>
state 절차는 pending → fulfilled or rejected 순이다. <br>
- pending : promise가 만들어져서 우리가 지정한 operation이 수행 중일 때를 말한다. <br>
- fulfilled : operation을 성공적으로 끝내 완벽하게 완료한 상태이다.<br>
- rejected: 파일을 찾을 수 없거나 문제가 발생한 상태이다.<br>

### producer와 consumer의 차이점
우리가 원하는 데이터를 제공하는 사람(producer)과 제공된 데이터를 쓰는 사람(consumer)의 다른 견해를 이해해야한다. 
<br><br>

<b>1. Producer</b><br>
원하는 기능을 비동기적으로 실행하는 Promise를 만들어보자.

```jsx
const promise = new Promise((resolve, reject)=>{
  setTimeout(()=>{
    resolve('promise를 성공적으로 수행함.');
  },2000);
});
//promise는 class이며, new키워드로 object 생성
//executor라는 콜백함수를 전달해줘야함.
//콜백함수에는 또다른 2가지의 콜백함수를 받음.
//resolve callback함수: 기능을 정상적으로 수행해서 마지막에 최종데이터를 전달.
//reject callback함수: 중간에 문제가 생기면 호출하는 함수.
```
    
보통 무거운 동작을 할 때, promise object를 사용한다.<br> 예를 들어 네크워크에서 데이터를 주고받는 동안, 동기적으로 작업을 수행하면 작업이 끝날때까지 다른 코드를 실행할 수 없다. <br>
따라서, 무거운 작업을 효율적으로 진행하려면 비동기적인 promise를 사용하는게 좋다.<br>

무거운 작업에는 네트워크 작업, 파일을 읽어오는 작업이 해당된다.<br>
<br>
⚠promise obejct를 생성한 동시에 executor콜백함수가 바로 실행된다.<br>
= 버튼을 눌렀을 때 네트워크 요청을 해야할 경우가 있다. <br>
이 때, 사용자가 요구하지도 않았는데 **불필요한 네트워크 통신이 발생**할 수 있다.

<br>

<b>2. Consumer</b><br>
then, catch, finally를 통해서 값을 받아올 수 있다. 

```jsx
const promise = new Promse((resolve, reject)=>{
  setTimeout(()=>{
    resolve('promise를 성공적으로 수행함.');
  },2000);
});

promise.then(value =>{
  console.log(value);
});
//값이 정상적으로 수행이 된다면 값을 받아올 거다.
//value값은 promise가 정상적으로 수행이 되어서
//resolve콜백함수에서 전달된 value값(promise를 성공적으로 수행함.)이 들어옴.
//2초 후, 'promise를 성공적으로 수행함.' 출력

```

```jsx
const promise = new Promse((resolve, reject)=>{
  setTimeout(()=>{
    reject(new Error('no network'));
});

promise.then(value =>{
  console.log(value);
});
//Uncaught Error 출력

promise.then(value =>{
  console.log(value);
})
.catch(error =>{
  console.log(error);
})
.finally(()=>{
  console.log('finally');
});
//Error: no network 출력
//finally 출력

//promise에서 then을 호출하게 되면
//다시 promise가 return이 되고,
//return된 promise에 catch를 등록하는 것.

//finally는 성공했든 실패했든 무조건 호출됨.
//따라서, 성공과 실패와 관련없이 마지막으로 기능을 수행하고 싶을 때 사용.
```

<br>

### Promise 연결하기(Promise chaining)

서버에서 숫자를 받아오는 새로운 프로젝트를 만들어보자. 

```jsx
const fechNumer = new Promise((resolve, reject)=>{
	setTimeout(()=> resolve(1),1000);
	//promise가 1초 후에 숫자 1을 전달.
})

fetchNumber
.then(num => num * 2)
.then(num => num * 3)
//then은 data뿐만 아니라 또다른 promise를 전달 가능.
.then(num =>{
	return new Promise((resolvee, reject) =>{
		setTimeout(()=> resolve(num-1),1000);
	});
//다른 서버에 보내서 다른 숫자로 변환된 값을 받아올 것.
//새로운 promise는 다른 서버랑 통신할 것.
//resolve로 num-1값을 전달.
})
.then(num=>console.log(num));
//최종적으로 3초 후에 숫자 5 출력 
```

<br>

### Promise error를 handling하는 방법

오류를 잘 처리해보는 방법에 대해 알아보자.<br>
아래는 서버에서 닭을 받아오고 달걀을 받아오고 요리까지 하는 예시이다.

```jsx
const getHen = () =>
	new Promise((resolve, reject)) =>{
		setTimeout(()=>resolve('🐓'),1000);
});

const getEgg = hen =>
	new Promise((resolve, reject)) =>{
		setTimeout(()=>resolve(`${hen} => 🥚`),1000);
});

const cook = egg =>
	new Promise((resolve, reject)) =>{
		setTimeout(()=>resolve(`${hen} => 🍳`),1000);
});

getHen()
	.then(hen => getEgg(hen))
	.then(egg => cook(egg))
	.then(meal => console.log(meal)); //최종적으로 만들어진 문자열이 출력되는 구간.

//3초 후에 🐓 => 🥚 => 🍳 출력

//<코드를 작성하는 TIP>
//callback함수를 전달할 때 받아오는 value를 
//함수 하나를 호출하는 경우, prettier에서 아래와 같이 줄여 쓴다.
//getHen().then(getEgg).then(cook).then(console.log);

//하지만 가독성이 안좋기 때문에 주석을 이용하여 여러줄로 쓰는게 좋다.
//getHen() //
// .then(getEgg)
// .then(cook)
// .then(console.log)
```

```jsx
const getHen = () =>
	new Promise((resolve, reject)) =>{
		setTimeout(()=>resolve('🐓'),1000);
});

const getEgg = hen =>
	new Promise((resolve, reject)) =>{
		setTimeout(()=>reject(new Error(`error! ${hen}=>🥚`)),1000);
});

const cook = egg =>
	new Promise((resolve, reject)) =>{
		setTimeout(()=>resolve(`${hen} => 🍳`),1000);
});

getHen() //
 .then(getEgg)
 .then(cook)
 .then(console.log)
 .catch(console.log)

//3초 후에 Error: error! 🐓 => 🥚 출력
```

```jsx
const getHen = () =>
	new Promise((resolve, reject)) =>{
		setTimeout(()=>resolve('🐓'),1000);
});

const getEgg = hen =>
	new Promise((resolve, reject)) =>{
		setTimeout(()=>reject(new Error(`error! ${hen}=>🥚`)),1000);
});

const cook = egg =>
	new Promise((resolve, reject)) =>{
		setTimeout(()=>resolve(`${hen} => 🍳`),1000);
});

getHen() //
 .then(getEgg)
 .then(error =>{
		return '🥖';
	})
//달걀을 받아오지 못해도 빵을 받아오도록 함.
 .then(cook)
 .then(console.log)
 .catch(console.log)

//3초 후에 🥖 =>  🍳

```

위 예시처럼 error로 인해 값을 받아오지 못했을 때를 대비해 catch를 활용해 값을 대체할 수 있다.<br>
즉, 전체적인 promise chain에 문제가 발생하지 않도록 catch로 구멍 처리를 할 수 있다.

<br>

### 콜백지옥 코드를 깔끔하게 변환하는 방법

아래는 콜백 지옥 코드이다.

```jsx
class UserStorage{
	loginUser(id, password, onSuccess, onError){
		setTimeout(()=>{
			if(id === 'kathy' && password === '0917')
			{
				onSuccess(id);
			}else{
				onError(new Error('not Found'));
				}
		},2000);
	}
}

getRoles(user, onSuccess, onError){
		setTimeout(()=>{
			if(user === 'kathy'){
				onSuccess({name : 'kathy', role: 'admin'});
			}else{
				onError(new Error('no access'));
			}
		})
}

const userStorage = new UserStorage();
const id = prompt('enter you id');
const pw = prompt('enter you pw');
userStorage.loginUser(
	id,
	password,
	user =>{
		userStorage.getRoles(
			user,
			userWithRole =>{
				alert(
					`${userWithRole.name}, you have a ${userWithRole.role}`;}`	
				);
			},
				error =>{
					console.log(error);
				}
		  );
	},
		error =>{
				console.log(error);
			}
)

```

<br>

아래는 promise를 이용하고, callback hell을 promise chaining으로 깔끔하게 바꾼 코드이다.

```jsx
class UserStorage{
	loginUser(id, password){
		return new Promise((resolve, reject)=>{
				setTimeout(()=>{
					if(id === 'kathy' && password === '0917'){
							resolve(id);
						}else{
								reject(new Error('not Found'));
						}
					},2000);		
		});

}

getRoles(user){
	return new Promise((resolve, reject) =>{
			setTimeout(()=>{
			if(user === 'kathy'){
				resolve({name : 'kathy', role: 'admin'});
			}else{
				reject(new Error('no access'));
			}
		}, 1000);
	
	})
	
}

const userStorage = new UserStorage();
const id = prompt('enter you id');
const pw = prompt('enter you pw');

userStroge
	.loginUser(id, password)
	.then(userStorage.getRoles)
	.then(user => alert(`${userWithRole.name}, you have a ${userWithRole.role}`;})
	.catch(console.log);

```
